apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fake-device-plugin
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: fake-device-plugin
subjects:
  - kind: ServiceAccount
    name: nvidia-device-plugin
    namespace: "{{ .Release.Namespace }}"
