apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fake-gpu-operator.device-plugin.common.metadata.name" . }}
  labels:
    {{- include "fake-gpu-operator.device-plugin.common.metadata.labels" . | nindent 4 }}
    run.ai/fake-node-deployment-template: "true"
spec:
  replicas: 0
  selector:
    {{- include "fake-gpu-operator.device-plugin.common.podSelector" . | nindent 4 }}
  template:
    metadata:
      {{- include "fake-gpu-operator.device-plugin.common.podTemplate.metadata" . | nindent 6 }}
    spec:
      {{- include "fake-gpu-operator.device-plugin.common.podTemplate.spec" . | nindent 6 }}