apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fake-status-updater
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - update
      - list
      - get
      - watch
      - create
      - delete
