{{- range $name, $profile := .Values.customProfiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-profile-{{ $name }}
  labels:
    fake-gpu-operator/gpu-profile: "true"
data:
  profile.yaml: |
{{ toYaml $profile | indent 4 }}
{{- end }}
