apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fake-status-updater
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
      - create
      - list
      - delete
  - apiGroups:
      - scheduling.run.ai
    resources:
      - podgroups
    verbs:
      - get