apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fake-status-updater
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: fake-status-updater
subjects:
  - kind: ServiceAccount
    name: status-updater
    namespace: "{{ .Release.Namespace }}"
