kind: PersistentVolume
apiVersion: v1
metadata:
  name: topology-pv
  labels:
    type: local
spec:
  storageClassName: "standard"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/topology/"