name: Enhancement
description: Suggest an idea for the Fake GPU Operator
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Fake GPU Operator feature-request form!
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        A clear and concise description of what you want to add to the Fake GPU Operator.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about and why they're less ideal.
    validations:
      required: false
  - type: markdown
    attributes:
      value: Love this feature? Give it a 👍 below.
