#!/usr/bin/env bash
#
# sync-profiles.sh — Pull GPU profiles from NVIDIA/k8s-test-infra and generate
# the built-in profile ConfigMaps for the fake-gpu-operator Helm chart.
#
# Usage:
#   hack/sync-profiles.sh                  # use default pinned version
#   hack/sync-profiles.sh v0.2.0           # override version
#
set -euo pipefail

REPO="https://github.com/NVIDIA/k8s-test-infra.git"
DEFAULT_VERSION="v0.1.0"
VERSION="${1:-$DEFAULT_VERSION}"
UPSTREAM_PATH="deployments/nvml-mock/helm/nvml-mock/profiles"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$REPO_ROOT/deploy/fake-gpu-operator/templates/profiles/builtin.yaml"

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "Cloning NVIDIA/k8s-test-infra @ ${VERSION} ..."
git -c advice.detachedHead=false clone --depth 1 --branch "$VERSION" \
    --filter=blob:none --sparse "$REPO" "$TMPDIR/upstream" 2>&1 \
    | grep -v "^Updating files"
cd "$TMPDIR/upstream"
git sparse-checkout set "$UPSTREAM_PATH" 2>/dev/null

PROFILES_DIR="$TMPDIR/upstream/$UPSTREAM_PATH"
if [ ! -d "$PROFILES_DIR" ] || [ -z "$(ls "$PROFILES_DIR"/*.yaml 2>/dev/null)" ]; then
    echo "ERROR: No profiles found at $UPSTREAM_PATH" >&2
    exit 1
fi

echo "Generating $OUTPUT_FILE ..."

FIRST=true
> "$OUTPUT_FILE"

echo "# Auto-generated by hack/sync-profiles.sh — do not edit manually." >> "$OUTPUT_FILE"
echo "# Source: NVIDIA/k8s-test-infra ${VERSION}" >> "$OUTPUT_FILE"

for profile_file in "$PROFILES_DIR"/*.yaml; do
    name="$(basename "$profile_file" .yaml)"
    echo "  - $name"

    if [ "$FIRST" = true ]; then
        FIRST=false
    else
        echo "---" >> "$OUTPUT_FILE"
    fi

    cat >> "$OUTPUT_FILE" <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-profile-${name}
  labels:
    run.ai/gpu-profile: "true"
data:
  profile.yaml: |
EOF

    # Indent every line of the upstream profile by 4 spaces
    sed 's/^/    /' "$profile_file" >> "$OUTPUT_FILE"
done

echo ""
echo "Done. Updated $(ls "$PROFILES_DIR"/*.yaml | wc -l | tr -d ' ') profiles from ${VERSION}."
echo "Review changes with: git diff deploy/fake-gpu-operator/templates/profiles/builtin.yaml"
