#!/usr/bin/env bash
#
# sync-profiles.sh — Pull GPU profiles from NVIDIA/k8s-test-infra and generate
# the built-in profile ConfigMaps for the fake-gpu-operator Helm chart.
#
# Usage:
#   hack/sync-profiles.sh                  # sync from upstream main (default)
#   hack/sync-profiles.sh v0.2.0           # override with a tag, branch, or commit SHA
#
set -euo pipefail

REPO="https://github.com/NVIDIA/k8s-test-infra.git"
# Default to main; the committed builtin.yaml + the header SHA are the pin.
# pcie_topology is main-only for now (no release has it). Override with a ref.
DEFAULT_VERSION="main"
VERSION="${1:-$DEFAULT_VERSION}"
UPSTREAM_PATH="deployments/nvml-mock/helm/nvml-mock/profiles"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$REPO_ROOT/deploy/fake-gpu-operator/templates/profiles/builtin.yaml"

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo "Cloning NVIDIA/k8s-test-infra @ ${VERSION} ..."
# Blobless+sparse clone then checkout, so VERSION may be a tag, branch, or SHA.
git -c advice.detachedHead=false clone \
    --filter=blob:none --sparse "$REPO" "$TMPDIR/upstream" 2>&1 \
    | grep -v "^Updating files" || true
cd "$TMPDIR/upstream"
git sparse-checkout set "$UPSTREAM_PATH" 2>/dev/null
git -c advice.detachedHead=false checkout "$VERSION" 2>&1 | grep -v "^Updating files" || true
RESOLVED_SHA="$(git rev-parse --short HEAD)"

PROFILES_DIR="$TMPDIR/upstream/$UPSTREAM_PATH"
if [ ! -d "$PROFILES_DIR" ] || [ -z "$(ls "$PROFILES_DIR"/*.yaml 2>/dev/null)" ]; then
    echo "ERROR: No profiles found at $UPSTREAM_PATH" >&2
    exit 1
fi

echo "Generating $OUTPUT_FILE ..."

FIRST=true
> "$OUTPUT_FILE"

echo '{{- if .Values.builtinProfiles.enabled }}' >> "$OUTPUT_FILE"
echo "# Auto-generated by hack/sync-profiles.sh — do not edit manually." >> "$OUTPUT_FILE"
echo "# Source: NVIDIA/k8s-test-infra ${VERSION} (commit ${RESOLVED_SHA})" >> "$OUTPUT_FILE"

for profile_file in "$PROFILES_DIR"/*.yaml; do
    name="$(basename "$profile_file" .yaml)"
    echo "  - $name"

    if [ "$FIRST" = true ]; then
        FIRST=false
    else
        echo "---" >> "$OUTPUT_FILE"
    fi

    cat >> "$OUTPUT_FILE" <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-profile-${name}
  labels:
    fake-gpu-operator/gpu-profile: "true"
data:
  profile.yaml: |
EOF

    # Indent every line of the upstream profile by 4 spaces
    sed 's/^/    /' "$profile_file" >> "$OUTPUT_FILE"
done

echo '{{- end }}' >> "$OUTPUT_FILE"

echo ""
echo "Done. Updated $(ls "$PROFILES_DIR"/*.yaml | wc -l | tr -d ' ') profiles from ${VERSION}."
echo "Review changes with: git diff deploy/fake-gpu-operator/templates/profiles/builtin.yaml"
