{{- if .Values.statusExporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-exporter
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  endpoints:
    - port: gpu-metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kwok-nvidia-dcgm-exporter
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: kwok-nvidia-dcgm-exporter
  endpoints:
    - port: gpu-metrics
      interval: 30s
      honorLabels: true
{{- end }}
