name: "[Internal] Set Dynamic Variables"

on:
  workflow_call:
    outputs:
      container_repo:
        description: "The container repository to use"
        value: ${{ jobs.set-vars.outputs.container_repo }}
      helm_repo:
        description: "The helm repository to use"
        value: ${{ jobs.set-vars.outputs.helm_repo }}
      version:
        description: "The version to use for tagging"
        value: ${{ jobs.set-vars.outputs.version }}

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      container_repo: ${{ steps.vars.outputs.container_repo }}
      helm_repo: ${{ steps.vars.outputs.helm_repo }}
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Set dynamic variables
        id: vars
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            # Version tag
            echo "container_repo=fake-gpu-operator-containers-prod" >> $GITHUB_OUTPUT
            echo "helm_repo=fake-gpu-operator-charts-prod" >> $GITHUB_OUTPUT
            echo "version=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
            # Pull request
            echo "container_repo=fake-gpu-operator-containers-lab" >> $GITHUB_OUTPUT
            echo "helm_repo=fake-gpu-operator-charts-lab" >> $GITHUB_OUTPUT
            echo "version=0.0.0-${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            # Push to main
            echo "container_repo=fake-gpu-operator-containers-test" >> $GITHUB_OUTPUT
            echo "helm_repo=fake-gpu-operator-charts-test" >> $GITHUB_OUTPUT
            echo "version=0.0.0-$GITHUB_SHA" >> $GITHUB_OUTPUT
          fi 
