apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fake-status-exporter
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: fake-status-exporter
subjects:
  - kind: ServiceAccount
    name: status-exporter
    namespace: "{{ .Release.Namespace }}"
