apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fake-gpu-operator.status-exporter.common.metadata.name" . }}
  labels:
    {{- include "fake-gpu-operator.status-exporter.common.metadata.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "fake-gpu-operator.status-exporter.common.podSelector" . | nindent 4 }}
  template:
    metadata:
      {{- include "fake-gpu-operator.status-exporter.common.podTemplate.metadata" . | nindent 6 }}
    spec:
      {{- include "fake-gpu-operator.status-exporter.common.podTemplate.spec" . | nindent 6 }}
      nodeSelector:
        nvidia.com/gpu.deploy.dcgm-exporter: "true"