apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: nvidia-dcgm-exporter
  name: nvidia-dcgm-exporter
spec:
  ports:
    - name: gpu-metrics
      port: 9400
      protocol: TCP
      targetPort: 9400
  selector:
    app: nvidia-dcgm-exporter
  type: ClusterIP
