{{ if .Values.environment.openshift }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fake-status-exporter
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - hostaccess
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fake-status-exporter
subjects:
- kind: ServiceAccount
  name: status-exporter
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fake-status-exporter
{{ end }}