apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mig-faker
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - update
      - list
      - watch