{{- if or .Values.gpuOperator.enabled .Values.nvidiaDraDriver.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvml-mock
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: fake-gpu-operator
    fake-gpu-operator/component: nvml-mock
{{- end -}}
