apiVersion: v1
kind: Service
metadata:
  name: topology-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: topology-server
  type: ClusterIP
  ports:
  - name: topology-server
    protocol: TCP
    port: 80
    targetPort: 8080