name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONTAINER_REGISTRY_URL: https://runai.jfrog.io/artifactory/fake-gpu-operator-containers-test
  HELM_REGISTRY_URL: https://runai.jfrog.io/artifactory/fake-gpu-operator-charts-test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Run tests
        run: make test

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    # Matrix of all components to build and push
    strategy:
      matrix:
        component: [
          device-plugin,
          status-updater,
          kwok-gpu-device-plugin,
          status-exporter,
          topology-server,
          mig-faker,
          jupyter-notebook
        ]
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.CONTAINER_REGISTRY_URL }}/{{ matrix.component }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.CONTAINER_REGISTRY_URL }}/cache/fake-gpu-operator:cache
          cache-to: type=registry,ref=${{ env.CONTAINER_REGISTRY_URL }}/cache/fake-gpu-operator:cache,mode=max

  # publish-helm-chart:
  #   runs-on: ubuntu-latest
  #   needs: [docker-build-and-push]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Helm login
