name: CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

env:
  CONTAINER_REGISTRY_TEST: https://runai.jfrog.io/artifactory/fake-gpu-operator-containers-test
  HELM_REGISTRY_TEST: https://runai.jfrog.io/artifactory/fake-gpu-operator-charts-test
  CONTAINER_REGISTRY_LAB: https://runai.jfrog.io/artifactory/fake-gpu-operator-containers-lab
  HELM_REGISTRY_LAB: https://runai.jfrog.io/artifactory/fake-gpu-operator-charts-lab

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Cache lint cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-lint-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-lint-
      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      - name: Run tests
        run: make test

  docker-release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    # Matrix of all components to build and push
    strategy:
      matrix:
        component: [
          device-plugin,
          status-updater,
          kwok-gpu-device-plugin,
          status-exporter,
          topology-server,
          mig-faker,
          jupyter-notebook
        ]
    steps:
      - name: Calculate Docker Repository
        id: repo
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "REPO=fake-gpu-operator-containers-lab" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event_name }} == 'push' && ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "REPO=fake-gpu-operator-containers-test" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event_name }} == 'push' && ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "REPO=fake-gpu-operator-containers-prod" >> $GITHUB_OUTPUT
          fi
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_ENDPOINT }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.ARTIFACTORY_ENDPOINT }}/${{ steps.repo.outputs.REPO }}/${{ matrix.component }}:${{ github.sha }}
          target: ${{ matrix.component }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.ARTIFACTORY_ENDPOINT }}/cache/fake-gpu-operator:cache
          cache-to: type=registry,ref=${{ secrets.ARTIFACTORY_ENDPOINT }}/cache/fake-gpu-operator:cache,mode=max

  # publish-helm-chart:
  #   runs-on: ubuntu-latest
  #   needs: [docker-build-and-push]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Helm login
